install.packages("caret")
install.packages("Ckmeans.1d.dp")
install.packages("DiagrammeR")
install.packages("e1071")
install.packages("precrec")
install.packages("xgboost")
devtools::install_github("thomasp85/ggforce")
devtools::install_github("liuyanguu/SHAPforxgboost")
install.packages("tidyverse")

